#!/bin/env bash

set -e


CPP_FILES=$(git diff --cached --name-only | grep -E '\.(cpp|hpp)$' || true)

if [ -n "$CPP_FILES" ]; then
    echo "Running clang-format.. ."

    echo "$CPP_FILES" | xargs clang-format -i

    git add "$CPP_FILES"

    echo "Running clang-tidy... "

    echo "$CPP_FILES" | xargs -n 1 clang-tidy
fi

echo "pre-commit checks passed"
