#!/bin/env bash

set -e

CPP_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|hpp)$' || true)

if [ -n "$CPP_FILES" ]; then
    echo "Running clang-format.. ."

    echo "$CPP_FILES" | xargs clang-format -i
    echo "$CPP_FILES" | xargs git add

    echo "Running clang-tidy... "

    echo $CPP_FILES | xargs -n 1 clang-tidy
fi

echo "pre-commit checks passed"
